spring.application.name=tesla

spring.config.import=optional:file:.env[.properties]
# Database Connection URL (change 'my_database' to your actual database name)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# MySQL JDBC Driver Class (Optional for modern Spring Boot versions as it auto-detects from URL)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
